doctrine_migrations:
    storage:
        table_storage:
            table_name: doctrine_migration_versions
            version_column_name: version
            version_column_length: 200
            executed_at_column_name: executed_at
            execution_time_column_name: execution_time
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/src/Migrations'

